patch_size: [4, 4]

ctx_sizes: [[7, 7], [8, 8], [8, 8], [8, 8]]
qry_sizes: [[4, 4], [4, 4], [4, 4], [4, 4]]

emb_dims: [128, 256, 512, 1024, 1024]
mlp_hidden_ratios: [4, 4, 4, 4]
n_heads: [4, 8, 16, 32]

n_layers_codec:
  forward: [[1, 1], [1, 1], [16, 2], [1, 1]]
  backward: null
attend_to_query:
  forward: [false, false, false, false]
  backward: null

qry_init_method: learnable
dropout: 0
use_flash_attn: true

n_passes: 1
use_aux: false