patch_size: [16, 16]

encoder:
  emb_dim: 768
  n_heads: 12
  n_layers: 12

decoder:
  emb_dim: 512
  n_heads: 16
  n_layers: 8

mlp_hidden_ratio: 4
dropout: 0
use_flash_attn: true

mask_ratio: 0.76
mask_size: [1, 1]
norm_tokens: true