patch_size: [4, 4]

ctx_sizes: [[4, 4], [4, 4]]
qry_sizes: [[2, 2], [2, 2]]

emb_dims: [48, 48, 48]
mlp_hidden_ratios: [4, 4]
n_heads: [4, 4]

n_layers_codec:
  forward: [[2], [2]]
  backward: [[1], [1]]
attend_to_query:
  forward: [true, true]
  backward: [true, true]

qry_init_method: learnable
dropout: 0
use_flash_attn: true

n_passes: 1
use_aux: false