patch_size: [4, 4]

ctx_sizes: [[4, 4], [4, 4], [2, 2]]

emb_dim: 128
mlp_hidden_ratios: [2, 2, 2]
n_heads: [4, 8, 16]

n_layers_stages: [2, 7, 2]
use_shifted_window: [true, false, false]

dropout: 0
drop_path: 0
use_flash_attn: true

add_abs_pos: false
add_rel_pos: true