patch_size: [4, 4]

ctx_sizes: [[4, 4], [4, 4]]
qry_sizes: [[2, 2], [2, 2]]

emb_dims: [48, 48, 48]
mlp_hidden_ratios: [4, 4]
n_heads: [4, 4]

n_layers_codec:
  forward: [[3], [3]]
  backward: [[2], [2]]
attend_to_query:
  forward: [true, true]
  backward: [true, true]

qry_init_method: learnable
dropout: 0
use_flash_attn: true

n_passes: 2
use_aux: false

local_mae: false
mae_steps:
  first_lvl: 1000
  factor: 1
mask_ratios: [0.75, 0.25]
norm_tokens: [true, false]