patch_size: [4, 4]

ctx_sizes: [[8, 8], [8, 8], [8, 8], [8, 8]]
qry_sizes: [[4, 4], [4, 4], [4, 4], null]

emb_dims: [96, 192, 384, 576, 576]
mlp_hidden_ratios: [4, 4, 4, 4]
n_heads: [3, 6, 12, 18, 18]

n_layers_stages: [[2, 1], [2, 1], [6, 1], [2]]

qry_init_method: linear_pool
dropout: 0
drop_path: 0.2
drop_cross_attn: false
use_flash_attn: true

add_abs_pos: true
add_rel_pos: false

shift_groups: false