patch_size: [16, 16]
ctx_sizes: [[4, 4]]
qry_sizes: [[2, 2]]

emb_dims: [768]
mlp_hidden_dims: [3072]
n_heads: [12]

qry_init_method: learnable
codec_steps_n_layers: [12]
attend_to_query: true
dropout: 0

use_flash_attn: true

n_passes: 2

mask_ratio: 0.75
norm_tokens: true