patch_size: [14, 14]
ctx_sizes: [[4, 4]]
qry_sizes: [[2, 2]]

emb_dims: [1280]
mlp_hidden_dims: [5120]
n_heads: [16]

qry_init_method: learnable
codec_steps_n_layers: [30]
attend_to_query: true
dropout: 0

use_flash_attn: true

n_passes: 2

mask_ratio: 0.75
norm_tokens: true