use_wandb: true

dataset:
  config_dir: imagenet
  config: full.yaml
  transform:
    train:
      config: rand_aug-256.yaml
    eval:
      config: eval-256.yaml

model:
  encoder:
    from_ssl: false
    config_dir: attn_pool2
    config: imagenet/base-4.yaml
    freeze: false
  head:
    config_dir: linear
    config: init_std=2e-5.yaml
  init:
    ckpt: null
    head: null

optimizer:
  config_dir: adamw
  config: b2=0.95.yaml
  lr:
    scale_with_batch: true
    lr: 1e-4
    decay:
      use: true
      warmup_epochs: 20
      epochs: null
      min: 0
      layer_decay: null
  weight_decay: 0.3

n_epochs: 300
batch_size: # tot % (per_wrk * n_wrk) = 0
  train:
    total: 4096
    per_worker: 64
  eval:
    per_worker: 128

mixup:
  mixup: 0.8
  cutmix: 1.0
  smoothing: 0.1