use_wandb: true

dataset:
  config_dir: imagenet
  config: full.yaml
  transform:
    train:
      config: rand_aug.yaml
    eval:
      config: eval.yaml

model:
  encoder:
    from_ssl: false
    config_dir: metaformer
    config: imagenet/cab36-sep-p=geme+conv-sep.yaml
    freeze: false
  head:
    config_dir: mlp
    config: init_std=2e-2-dropout=0.5.yaml
  init:
    ckpt: null
    head: null

optimizer:
  config_dir: lamb
  config: null
  lr:
    scale_with_batch: true
    lr: 5e-4 # lr = lr * tot_batch_size / 256
    decay:
      use: true
      warmup_epochs: 20
      epochs: null
      min: 1e-5
      layer_decay: null
  weight_decay: 0.05

n_epochs: 300
batch_size: # tot % (per_wrk * n_wrk) = 0
  train:
    total: 4096
    per_worker: 32
  eval:
    per_worker: 64

mixup:
  mixup: 0.8
  cutmix: 1.0
  smoothing: 0.1