use_wandb: true

dataset:
  config_dir: imagenet
  config: full.yaml
  transform:
    train:
      config: rand_aug.yaml
    eval:
      config: eval.yaml

model:
  encoder:
    from_ssl: false
    config_dir: unet1_enc
    config: null
    freeze: false
  head:
    config_dir: linear
    config: init_std=2e-5.yaml
  init:
    ckpt: null
    head: null

optimizer:
  config_dir: adamw
  config: b2=0.95.yaml
  lr:
    scale_with_batch: true
    lr: 1e-4
    decay:
      use: true
      warmup_epochs: 20
      epochs: null
      min: 0
      layer_decay: null
  weight_decay: 0.3

n_epochs: 300
batch_size:
  train: # tot % (per_wrk * n_wrk) = 0
    total: 4096
    per_worker: 64
  eval:
    per_worker: 128