use_wandb: true

dataset:
  config_dir: imagenet
  config: full.yaml
  transform:
    train:
      config: rand_crop_scale=0.08-1.yaml
    eval:
      config: eval.yaml

model:
  encoder:
    from_ssl: true
    config_dir: mae_unet1
    config: imagenet/c1.yaml
    freeze: true
  head:
    config_dir: linear
    config: init_std=1e-2.yaml
  init:
    ckpt: ssl/imagenet/test1
    head: false

optimizer:
  config_dir: adamw
  config: b2=0.999.yaml
  lr:
    scale_with_batch: true
    lr: 0.1
    decay:
      use: true
      warmup_epochs: 10
      epochs: null
      min: 0
      layer_decay: null
  weight_decay: 0

n_epochs: 90
batch_size:
  train: # tot % (per_wrk * n_wrk) = 0
    total: 4096
    per_worker: 512
  eval:
    per_worker: 512