patch_size: [16, 16]

ctx_sizes: [[4, 4], [4, 4], [4, 4]]
qry_sizes: [[2, 2], [2, 2], [2, 2]]

emb_dims: [768, 768, 768, 768]
mlp_hidden_ratios: [4, 4, 4]
n_heads: [12, 12, 12]

n_layers_codec:
  forward: [[3], [3], [3]]
  backward: [[1], [1], [1]]
attend_to_query:
  forward: [true, true, true, true]
  backward: [true, true, true, true]

qry_init_method: learnable
dropout: 0
use_flash_attn: true

n_passes: 2
use_aux: false