patch_size: [4, 4]

ctx_sizes: [[8, 8], [8, 8], [8, 8], [8, 8]]
qry_sizes: [[4, 4], [4, 4], [4, 4], [4, 4]]

emb_dims: [128, 256, 512, 1024, 1024]
mlp_hidden_ratios: [4, 4, 4, 4]
n_heads: [4, 8, 16, 32]

n_layers_codec:
  forward: [[3], [3], [3], [3]]
  backward: [[1], [1], [1], [1]]
attend_to_query:
  forward: [true, true, true, true]
  backward: [true, true, true, true]

qry_init_method: learnable
dropout: 0
use_flash_attn: true

n_passes: 2
use_aux: false

local_mae: true
mae_steps:
  first_lvl: 1
  factor: 1
mask_ratios: [0.5, 0.5, 0.5, 0.5]
norm_tokens: [true, true, true, true]