patch_size: [4, 4]

emb_dims: [64, 128, 320, 512]
depths: [2, 2, 6, 2]

stem: {name: linear}

poolings:
  - {name: avg, kernel_size: 3, stride: 2, padding: 1}
  - {name: avg, kernel_size: 3, stride: 2, padding: 1}
  - {name: avg, kernel_size: 3, stride: 2, padding: 1}

token_mixers:
  - {name: avg, kernel_size: 3}
  - {name: avg, kernel_size: 3}
  - {name: avg, kernel_size: 3}
  - {name: avg, kernel_size: 3}

norm_spatial: true
drop_path: 0.1