patch_size: [4, 4]

emb_dims: [64, 128, 320, 512]
depths: [2, 2, 6, 2]

stem: {name: single_conv}

poolings:
  - {name: conv, kernel_size: 2, stride: 2, padding: 0}
  - {name: conv, kernel_size: 2, stride: 2, padding: 0}
  - {name: conv, kernel_size: 2, stride: 2, padding: 0}

token_mixers:
  - {name: avg, kernel_size: 3}
  - {name: avg, kernel_size: 3}
  - {name: avg, kernel_size: 3}
  - {name: avg, kernel_size: 3}

norm_spatial: true
drop_path: 0.1