patch_size: [4, 4]

emb_dims: [96, 192, 384, 768]
depths: [6, 6, 18, 6]

stem: {name: single_conv}

poolings:
  - {name: conv, kernel_size: 3, stride: 2, padding: 1}
  - {name: conv, kernel_size: 3, stride: 2, padding: 1}
  - {name: conv, kernel_size: 3, stride: 2, padding: 1}

token_mixers:
  - {name: avg, kernel_size: 3}
  - {name: avg, kernel_size: 3}
  - {name: avg, kernel_size: 3}
  - {name: avg, kernel_size: 3}

norm_spatial: true
drop_path: 0.3